### ISSUE TITLE
pip install is broken

### ISSUE THREAD

**Issue by kangstarr** [djieff/ocio-lut-prescription#1]
when running `pip install ocio-lut-prescription` it doesn't download certain required files such as the following:
./ui/main_window.ui
./ui/icon.png
./ui/resource.qrc

Due to main_window.ui not being downloaded during the pip install process, the python application errors out

**Comment by djieff** [comment]
Hi @kangstarr 

Thanks for letting me know, and giving me details about the issue.
Let me come back to you as soon as possible,


JF

**Comment by djieff** [comment]
hi @kangstarr 

Thanks for the wait and patience, I fixed this issue.
JF
